;;; nagy.el --- -*- lexical-binding: t; -*-
(require 'nagy-company nil t)
(require 'nagy-corfu nil t)
(require 'nagy-devops nil t)
(require 'nagy-dired nil t)
(require 'nagy-elfeed nil t)
(require 'nagy-elpher nil t)
(require 'nagy-emacs nil t)
(require 'nagy-evil nil t)
(require 'nagy-formats nil t)
(require 'nagy-hy nil t)
(require 'nagy-lsp nil t)
(require 'nagy-lua nil t)
(require 'nagy-magit nil t)
(require 'nagy-misc nil t)
(require 'nagy-modus-themes nil t)
(require 'nagy-nix nil t)
(require 'nagy-nlinum nil t)
(require 'nagy-org nil t)
(require 'nagy-pcap-converter nil t)
(require 'nagy-qrcode nil t)
(require 'nagy-rust nil t)
(require 'nagy-text nil t)
(require 'nagy-use-package nil t)
(require 'nagy-vertico nil t)
(require 'nagy-web nil t)
(provide 'nagy)
;;; nagy.el ends here
