;;; nagy.el --- -*- lexical-binding: t; -*-

(require 'nagy-common-lisp nil t)
(require 'nagy-corfu nil t)
(require 'nagy-dired nil t)
(require 'nagy-elpher nil t)
(require 'nagy-emacs nil t)
(require 'nagy-evil nil t)
(require 'nagy-exwm nil t)
(require 'nagy-formats nil t)
(require 'nagy-gc nil t)
(require 'nagy-haskell nil t)
(require 'nagy-hy nil t)
(require 'nagy-lispy nil t)
(require 'nagy-list nil t)
(require 'nagy-lsp nil t)
(require 'nagy-magit nil t)
(require 'nagy-mail nil t)
(require 'nagy-media nil t)
(require 'nagy-misc nil t)
(require 'nagy-misc2 nil t)
(require 'nagy-mode-line nil t)
(require 'nagy-modus-themes nil t)
(require 'nagy-nix nil t)
(require 'nagy-org nil t)
(require 'nagy-pcap-converter nil t)
;; (require 'nagy-qrcode nil t)
(require 'nagy-tablist nil t)
(require 'nagy-text nil t)
(require 'nagy-url nil t)
(require 'nagy-use-emacs nil t)
(require 'nagy-use-package nil t)
(require 'nagy-vertico nil t)
(require 'nagy-web nil t)

(provide 'nagy)
;;; nagy.el ends here
